import type { EmailMessage } from "./email";

type LeaveDetails = { startDate: string; endDate: string; hours: number; appUrl: string; id: string };
const range = (details: LeaveDetails) => `${details.startDate} to ${details.endDate} (${details.hours} hours)`;

export function leaveSubmittedEmail(to: string, details: LeaveDetails): EmailMessage { return { to, subject: "Leave request submitted", text: `Your leave request for ${range(details)} is pending approval.\n\nView your leave: ${details.appUrl}/leave`, tag: "leave-submitted", idempotencyKey: `leave-submitted-${details.id}` }; }
export function managerApprovalEmail(to: string, employeeName: string, details: LeaveDetails): EmailMessage { return { to, subject: "Leave request awaiting approval", text: `${employeeName} submitted a leave request for ${range(details)}.\n\nReview the request: ${details.appUrl}/manager/requests/${details.id}`, tag: "approval-required", idempotencyKey: `approval-required-${details.id}` }; }
export function leaveDecisionEmail(to: string, decision: "APPROVED" | "REJECTED", details: LeaveDetails): EmailMessage { return { to, subject: `Leave request ${decision === "APPROVED" ? "approved" : "rejected"}`, text: `Your leave request for ${range(details)} was ${decision.toLowerCase()}.\n\nView your leave: ${details.appUrl}/leave`, tag: `leave-${decision.toLowerCase()}`, idempotencyKey: `leave-${decision.toLowerCase()}-${details.id}` }; }
export function leaveCancelledEmail(to: string, details: LeaveDetails, requiresReview: boolean): EmailMessage { return { to, subject: requiresReview ? "Leave cancellation requested" : "Leave request cancelled", text: `${requiresReview ? "Your cancellation request is awaiting review" : "Your leave request was cancelled"}: ${range(details)}.\n\nView your leave: ${details.appUrl}/leave`, tag: requiresReview ? "cancellation-requested" : "leave-cancelled", idempotencyKey: `leave-cancellation-${details.id}` }; }
export function managerCancellationEmail(to: string, employeeName: string, details: LeaveDetails): EmailMessage { return { to, subject: "Approved leave cancellation requested", text: `${employeeName} requested cancellation of approved leave for ${range(details)}.\n\nReview team leave: ${details.appUrl}/manager`, tag: "cancellation-review", idempotencyKey: `cancellation-review-${details.id}` }; }
